name: Test

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Ruby Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        id: install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
    
      - name: Lint
        id: lint
        continue-on-error: true
        run: bundle exec rubocop
  
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Ruby Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        id: install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Unit Tests
        id: unit
        run: bundle exec rake test:unit
      
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Ruby Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        id: install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Integration Tests 
        id: integration
        run: bundle exec rake test:uat:integration

  test-cloudprovider-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Ruby Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        id: install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Cloud Provider Tests (Azure)
        id: azure
        run: bundle exec rake test:uat:azure

  test-cloudprovider-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.4'

      - name: Ruby Gem Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Gems
        id: install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
  
      - name: Cloud Provider Tests (AWS)
        id: aws
        run: bundle exec rake test:uat:aws
  
  slack-notify:
    runs-on: ubuntu-latest
    needs: [lint, test-unit, test-integration, test-cloudprovider-aws, test-cloudprovider-azure]
    if: ${{ always() }}
    steps:
      - name: Build Result Slack Notification
        uses:  8398a7/action-slack@v3
        with:
          author_name: GitHub Actions
          status: custom
          fields: commit,repo,ref,author,eventName,message,workflow
          custom_payload: |
            {
              username: "GitHub Actions",
              icon_emoji: ":octocat:",
              attachments: [{
                color: ${{ 
                  needs.lint.result == 'success' &&
                  needs.test-unit.result == 'success' &&
                  needs.test-integration.result == 'success' &&
                  needs.test-cloudprovider-azure.result == 'success' &&
                  needs.test-cloudprovider-aws.result == 'success'
                }} === true ? '#43cc11' : '#e05d44',
                blocks: [
                  {
                    type: "section",
                    text: {
                      type: "mrkdwn",
                      text: `Build for ${process.env.AS_REPO}`
                    }
                  },
                  {
                    type: "section",
                    fields: [
                      {
                        type: "mrkdwn",
                        text: `*Commit:*\n${process.env.AS_COMMIT}`
                      },
                      {
                        type: "mrkdwn",
                        text: `*Author:*\n${process.env.AS_AUTHOR}`
                      },
                      {
                        type: "mrkdwn",
                        text: `*Branch:*\n${process.env.AS_REF}`
                      },
                      {
                        type: "mrkdwn",
                        text: `*Message:*\n${process.env.AS_MESSAGE}`
                      },
                      {
                        type: "mrkdwn",
                        text: `*Type:*\n${process.env.AS_EVENT_NAME}`
                      },
                      {
                        type: "mrkdwn",
                        text: "*PR:*\n${{ github.event.pull_request.html_url }}"
                      },
                      {
                        type: "mrkdwn",
                        text: `*Workflow:*\n${ process.env.AS_WORKFLOW }`
                      }
                    ]
                  },
                  {
                    type: "section",
                    text: {
                      type: "mrkdwn",
                      text: [
                        "*Result:*",
                        `• ${ ${{ needs.lint.result == 'success' }} === true ? '✅' : '❌' } Install dependencies: ${{ needs.lint.result }}`,
                        `• ${ ${{ needs.test-unit.result == 'success' }} === true ? '✅' : '❌' } Lint: ${{ needs.test-unit.result }}`,
                        `• ${ ${{ needs.test-integration.result == 'success' }} === true ? '✅' : '❌' } Unit test: ${{ needs.test-unit.result }}`,
                        `• ${ ${{ steps.integration.outcome == 'success' }} === true ? '✅' : '❌' } Integration test: ${{ steps.test-integration.outcome }}`,
                        `• ${ ${{ needs.test-cloudprovider-azure.result == 'success' }} === true ? '✅' : '❌' } AWS cloud provider test: ${{ needs.test-cloudprovider-azure.result }}`,
                        `• ${ ${{ needs.test-cloudprovider-aws.result == 'success' }} === true ? '✅' : '❌' } Azure cloud provider test: ${{ needs.test-cloudprovider-aws.result }}`
                      ].join('\n')
                    }
                  },
                  {
                    type: "context",
                    elements: [
                      {
                        type: "image",
                        image_url: "https://avatars2.githubusercontent.com/in/15368",
                        alt_text: "Github Actions"
                      },
                      {
                        type: "mrkdwn",
                        text: "This message was created automatically by GitHub Actions."
                      }
                    ]
                  }
                ]
              }]
            }
        env:
          GITHUB_TOKEN: ${{ github.token }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
  
        